#########################################################################
# Title:         Community: Gaps Role                                   #
# Author(s):     TheBradz, chazlarson                                   #
# URL:           https://github.com/Cloudbox/Community                  #
# Docker Image:  housewrecker/gaps:latest                               #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    record: gaps
  when: cloudflare_enabled

- name: Create htpasswd
  htpasswd:
    path: "/opt/nginx-proxy/htpasswd/{{ item }}.{{ user.domain }}"
    name: "{{ user.name }}"
    password: "{{ user.pass }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
  with_items:
    - gaps

- name: Stop and remove any existing container
  docker_container:
    name: gaps
    state: absent

- name: Create gaps directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/gaps

- name: Create and start container
  docker_container:
    name: gaps
    image: housewrecker/gaps:latest
    pull: yes
    published_ports:
      - "127.0.0.1:8484:8484"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "gaps.{{ user.domain }}"
      VIRTUAL_PORT: "8484"
      VIRTUAL_PROTO: "https"
      LETSENCRYPT_HOST: "gaps.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes:
      - "/opt/gaps:/usr/data"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - gaps
    purge_networks: yes
    restart_policy: unless-stopped
    state: started

#docker run -d -p 8484:8484 --name mygaps --expose 32400 -v /{localFolder}/gaps:/usr/data housewrecker/gaps:latest